---
apiVersion: v1
kind: Namespace
metadata:
  name: psp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: psp-sa
  namespace: psp
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-role
  namespace: psp
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - create
      - update
      - put
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-vault
  namespace: psp
subjects:
  - kind: ServiceAccount
    name: psp-sa
roleRef:
  kind: Role
  name: psp-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: secure-flask
  namespace: psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    container.apparmor.security.beta.kubernetes.io/secure-vul-flask: localhost/k8s-vul-flask-redis-armor
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  labels:
    app: secure-flask
spec:
  serviceAccountName: psp-sa
  securityContext:
    runAsUser: 10001
    runAsGroup: 3000
    fsGroup: 2000
    runAsNonRoot: true
  containers:
    - name: secure-vul-flask
      image: <image-name>
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsGroup: 2000
        runAsUser: 10001
        capabilities:
          drop:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - NET_RAW
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
        privileged: false
        readOnlyRootFilesystem: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "256m"
        limits:
          memory: "512Mi"
          cpu: "512m"
      ports:
        - containerPort: 5000
          name: vulflask-port
  automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: psp-svc
  namespace: psp
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: secure-flask